# Generated by Django 4.2.5 on 2023-09-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family_member',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
