# Generated by Django 3.2.21 on 2023-11-09 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_rename_second_name_family_member_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family_member',
            name='last_name',
        ),
    ]
