# Generated by Django 3.2.21 on 2023-11-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_remove_family_member_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_member',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates'),
        ),
        migrations.AddField(
            model_name='family_member',
            name='data_coordinates',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
