# Generated by Django 3.2.21 on 2023-11-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_auto_20231130_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_member',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
