# Generated by Django 3.2.21 on 2023-12-06 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_alter_family_member_certificate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family_member',
            old_name='first_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='family_member',
            name='data_coordinates',
        ),
    ]
