# Generated by Django 3.2.21 on 2024-01-28 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_auto_20231206_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family_member',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='family_member',
            name='user_name',
        ),
        migrations.AddField(
            model_name='family_member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='family_member',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='family_member',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='family_member',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trees.family_member'),
        ),
    ]
