# Generated by Django 3.2.21 on 2024-01-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0007_auto_20240128_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family_member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
