# Generated by Django 3.2.21 on 2024-01-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0008_alter_family_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_member',
            name='children',
            field=models.ManyToManyField(related_name='parents', to='trees.Family_Member'),
        ),
    ]
