# Generated by Django 3.2.21 on 2024-01-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0011_alter_family_member_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family_member',
            name='children',
        ),
        migrations.RemoveField(
            model_name='family_member',
            name='gender',
        ),
        migrations.AddField(
            model_name='family_member',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='family_member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='family_member',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='family_member',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='trees.family_member'),
        ),
    ]
