# Generated by Django 3.2.21 on 2024-01-30 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0012_auto_20240130_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family_member',
            name='certificate_image',
        ),
        migrations.RemoveField(
            model_name='family_member',
            name='parent',
        ),
        migrations.AddField(
            model_name='family_member',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='trees.family_member'),
        ),
    ]
