# Generated by Django 3.2.21 on 2024-01-31 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0013_auto_20240130_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family_member',
            old_name='name',
            new_name='parent',
        ),
        migrations.AlterField(
            model_name='family_member',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='trees.family_member'),
        ),
    ]
