# Generated by Django 3.2.21 on 2024-01-31 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0014_auto_20240131_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family_member',
            old_name='parent',
            new_name='name',
        ),
    ]
